---
- name: update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: install virtualization tools
  apt: name={{item}} state=present
  with_items:
    - qemu-kvm
    - libvirt-clients
    - libvirt-daemon-system
    - vagrant