---
- hosts: chroots
  vars_files:
    - ../vars/var_file.yml
  vars:
    proxy_env:
      LC_ALL: C
  connection: chroot
  roles:
    - common
    - nfs
    - desktop
    
- hosts:
    - /chroots/debian-dev
  connection: chroot
  roles: 
    - dev
    - virt